### ISSUE TITLE
Is it offline forever?

### ISSUE THREAD

**Issue by julianpoelmann** [dorythecat/TransforMate#18]
Idk the bot appears to be offline

**Comment by dorythecat** [comment]
The bot should be back up, I believe? Please let me know if it goes down again, thank you

**Comment by julianpoelmann** [comment]
It is back up but I did notice that half of the commands make the bot respond with "application did not respond". If it's still in development then I understand

**Comment by dorythecat** [comment]
Oh, nope, that shouldn't happen. I will reopen this issue until that's fixed.

**Comment by julianpoelmann** [comment]
Alrighty! Thankies in advance

**Comment by dorythecat** [comment]
The bot should be back online and working, please test and notify me. Thanks in advance.

**Comment by julianpoelmann** [comment]
Still errors out oof
![Screenshot_2024-12-21-11-32-20-60_ae4b61cddc56e7894f225aea7d9147d6.jpg](https://github.com/user-attachments/assets/f92be006-836a-436b-bbd8-9705d9d8665f)

**Comment by dorythecat** [comment]
![image](https://github.com/user-attachments/assets/842be88e-9419-4d47-abc4-8bd2092d83e6)
Seems like an issue with key values, where is the command being run?

**Comment by dorythecat** [comment]
(Line 144 of utils.py btw)

**Comment by julianpoelmann** [comment]
It happens with sprinkle, hush and a few others I think

**Comment by dorythecat** [comment]
I assume the user was unclaimed? If so, I think I know the fix. Will be doing a trial and pushing changes soon.

**Comment by julianpoelmann** [comment]
The claiming command is also broken

**Comment by dorythecat** [comment]
Yeah I believe I know what the problem is, pushing asap

**Comment by dorythecat** [comment]
Please test again and let me know if it works now.

**Comment by julianpoelmann** [comment]
We tested a lil more

It still doesn't work but we noticed the claim command does respond when someone isn't changed but when they are changed the bot simply fails to respond

**Comment by dorythecat** [comment]
hmmm, okay, I'll have a look, brb

**Comment by dorythecat** [comment]
I have done a full cache wipeout, please test again

**Comment by julianpoelmann** [comment]
Still errors qwq

**Comment by dorythecat** [comment]
Nope, was an error on my side, sorry, try again

**Comment by julianpoelmann** [comment]
The tf command stopped working

**Comment by dorythecat** [comment]
And another fail on the serrver end, sorry, try again, should work now

**Comment by julianpoelmann** [comment]
Still doesn't work, maybe it's an idea if I invite you to it?

**Comment by dorythecat** [comment]
Maybe try the command again? This error seems weird...

**Comment by julianpoelmann** [comment]
Tf worked, claim doesn't

**Comment by dorythecat** [comment]
Oh, this seems to be an issue with unfinished code, TL;DR: the sstem was being weitched from one data structure to anoither and it seems like I forgot finishing the switch. This is a big issue, so I'll sadly take a bit to fix it. Sorry for the inconvinience.

**Comment by julianpoelmann** [comment]
Hey hey no need rush

**Comment by dorythecat** [comment]
We will no longer be providing official support for the bot, so I'm sorry to say, this issue won't be fixed in the near future.
